Feature/choose color & Navigation
Katemuya/Capstone-Project pull request #18
Opened 2023-07-10 14:11 UTC by Katemuya

2023-07-10 14:43 UTC, actyvystom requested changes
Well done! 👍🏻 
See a comment on `moment` and other date libraries - 
and your tests fail. Either remove all tests (the one failing came with the capstone template and is outdated due to a changed Heading component) or adjust them to run correctly. 
Cheers, Thomas

2023-07-10 14:43 UTC, actyvystom commented on components/Calendar/index.js
>  import moment from "moment";
What are you using `moment` for? This is a very outdated library, they state themselves on their website that there are better alternatives nowadays, see https://momentjs.com/docs/#/-project-status/recommendations/
As you are using already other date libraries (and `moment` does not even show up as dependency in your `package.json` 🤔), I suggest to get remove it and use the date libraries you already rely on in your dependencies (`date-fns` etc.)

2023-07-12 10:11 UTC, Katemuya commented
This is a bit chaotic because of many last minute and crucial changes so please bare with me. The tests fail because I removed the existing ones and I am yet to write my own.

2023-07-12 10:45 UTC, ArnelaKapllani commented
Hi @Katemuya, you have done a really good job till now.
According to the last commits, I can't find anything to comment on so you have a green hook from me 😊

2023-07-12 10:53 UTC, Katemuya commented
Thanks alot @ArnelaKapllani . I wish you all the best ahead 🤗

2023-07-12 17:33 UTC, merged